name: SkyDash CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install uv
      run: pip install uv

    - name: Cache uv packages
      uses: actions/cache@v4
      with:
        path: .uv
        key: ${{ runner.os }}-uv-${{ hashFiles('pyproject.toml') }}

    - name: Create virtual environment with uv
      run: uv venv .venv

    - name: Activate virtualenv
      run: source .venv/bin/activate

    - name: Install dependencies with uv
      run: uv pip install -r pyproject.toml

    - name: Install test/lint tools
      run: uv pip install flake8 pytest

    - name: Lint with flake8
      run: |
        flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 src --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        pytest src
